PORTNAME=	libsnet
PORTVERSION=	1.1.0.2
CATEGORIES=	net
MASTER_SITES=	file://not.currently.available/

MAINTAINER=	simta@umich.edu
COMMENT=	Simple TCP communications library

GNU_CONFIGURE=	yes
USE_OPENSSL=    yes
USES=		libtool pathfix

INSTALL_TARGET=	install-strip

.include <bsd.port.mk>
